### PR TITLE
Try make dnsrecon a better python module

### PR DESCRIPTION
**Pull request by buzzdeee**
tried to follow this: https://docs.python-guide.org/writing/structure/
and took inspiration from other python modules.

While I tried to create a port for OpenBSD, I was pointed out that the port spills it's files all over
the python site-packages directory after installation. As it's my first trial with python setuptools,
and it's structure, it took me a while to get things straight.

Changes are mostly:

- create dnsrecon directory
- move dnsrecon.py into dnsrecon/cli.py
- move __init__.py into dnsrecon dir
- move lib/ dir into dnsrecon dir
- create dnsrecon/__main__.py
- update setup.py, create proper entry point, and to exclude tests directory from installation.
- update import statements in .py files under dnsrerecon dir where needed to let everything find what it needs
- delete bin/dnsrecon

With that, dnsrecon should also properly install with pip, and might also help other packagers getting it packaged for other OS/Distributions.

### CODE REVIEW

**Comment by buzzdeee** [comment]
the force-push should have fixed the blank line at EOF lint error

**Comment by buzzdeee** [comment]
the last force-push should hopefully get the tests right as well

**Comment by L1ghtn1ng** [comment]
Can you fix the merge conflicts please?

**Comment by buzzdeee** [comment]
@L1ghtn1ng 

should not be mergeable.

**Comment by L1ghtn1ng** [comment]
Thanks for this

**Pull request merged**
