### PR TITLE
Modified the RVL lists to process hosts in groups to avoid OOM killer with large RFC1918 class A address ranges.

### PR DESCRIPTION
**Pull request by unixrox**
The Linux OOM killer will come into play for large address space (I.e., RFC 1918 Class A address space - 10.10.10.10/8) when using reverse look ups (PTR) on hosts with even 32GB's of RAM. Recon is everything to us at Truvantis, because you can't protect or defend yourself from what you don't know about, so this was something we had to address, especially when targeting all the internal things during comprehensive penetration tests and attack surface analysis. This patch appears to resolve this specific issue, utilizing a small memory footprint while returning identified data quicker, all without significant memory impact. Approval to release this has been granted as it benefits the entire community. We hope you find this beneficial and thank you for your contribution to our community.

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
Thanks for this, can you also please make the same changes in just the normal dnsrecon.py as well please as they are the same as the binary is used as part of the install when you do setup.py install

**Comment by unixrox** [comment]
Ah! My bad. That makes sense.

**Comment by unixrox** [comment]
Looks like some of the validation checks failed for some versions of python due to the missing space around the operator. I believe I also simply hacked my way around this problem by modifying the bin file, and mixing the bin and the python file, without regarding the difference between the bin file and the python file. Do you want me to pull this down again, modify only the specific sections, include the space around the operator and comment/commit?

**Comment by unixrox** [comment]
I decided to pull down the file and make the specific changes I intended to make. There are differences between the bin and the python file, but they are not mine. Hopefully this helps. Let me know if you need anything else from me and thank you for what you do for the community!

**Comment by L1ghtn1ng** [comment]
Thank you for the kind words

**Pull request merged**
