### PR TITLE
Reviewed zone_transfer() function

### PR DESCRIPTION
**Pull request by filippolauria**
I have tested the reviewed method against zonetransfer.me and megacorpone.com.
It seemed to work fine.

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
Are you able to write a unit test for this with pytest by any chance?

**Comment by L1ghtn1ng** [comment]
Would like to start getting unit test

**Comment by filippolauria** [comment]
i can't promise anything, because of the lack of time, but I will try

**Comment by L1ghtn1ng** [comment]
@filippolauria any progress on getting the unit test done?

**Comment by filippolauria** [comment]
@L1ghtn1ng i managed to complete it (with a few other fixes). Take a look!

**Comment by L1ghtn1ng** [comment]
If the commented out stuff is not needed anymore please remove it

**Comment by filippolauria** [comment]
Sure. I have made a sort of refactoring of the DnsHelper class too.

**Comment by L1ghtn1ng** [comment]
Can you add it to the GitHub action workflow to run the test please with pytest

**Comment by L1ghtn1ng** [comment]
Can you add it to https://www.github.com/darkoperator/dnsrecon/tree/master/.github%2Fworkflows%2FDNSrecon.yml

**Comment by filippolauria** [comment]
Check it out. Also, I don't understand why flake8 keeps complaining.

**Comment by L1ghtn1ng** [comment]
If you run the flake8 command that is in the workflow you should see why

**Comment by filippolauria** [comment]
I ran exactly those commands. It complains about "import re", but that statement is not contained in the files of this few commits.

**Comment by L1ghtn1ng** [comment]
Yeah it will complain no matter what till it is fixed and what does the message output say from flake8?
________________________________

**Comment by filippolauria** [comment]
This is what you get here on github:
image

and this is what I get on my VM:
image

**Comment by L1ghtn1ng** [comment]
That is interesting no idea what is going on there then

**Comment by filippolauria** [comment]
Maybe I figured it out. Github says that the branches have no conflicts in terms of "mergeability". But when they are merged flake8 complains. The solution could be the following: you can merge this pull request, then I will sync my forked repo (which is the actual repo I work on) to this, and try to solve this conflict manually (which probably means I will manually remove the "import re" from dnshelper.py).

**Pull request merged**
