### PR TITLE
Return SOA records for subdomains.

### PR DESCRIPTION
**Pull request by FrankSpierings**
This is not perfect, but it will help to return SOA records for subdomains.

### CODE REVIEW

**Comment by darkoperator** [comment]
Still trying to understand the why of this, for instance it is not using the DNS server a user would set but the default one of the system. So you would not be getting the SOA for the zone file of that server but getting the SOA at another one in the zone delegation. What was the error that prompted you to do the query by hand and use the system default server?

**Comment by FrankSpierings** [comment]
Well if you do a 'dig soa <name>', it will return the SOA record in the AUTHORITY section, while dnsrecon lets you believe that there is 'no' authorative nameserver for the given name, which is not actually true. So this is my reason for the implementation. 

```dig soa www.google.com``` will return no answer to the query, but will specify the authorative name server in the additional section.
``` python dnsrecon.py -d www.google.com``` will return:
"Could not Resolve SOA Record for www.google.com"

**Comment by darkoperator** [comment]
Can you send me some PCAPs I want to see what dig does and what dnsrecon does. I will have to test and make sure that is I give it a specific name server it will not try to use the one in configured in the host for calls.

**Comment by FrankSpierings** [comment]
I've send the captures through email. They look similar.

The call you used to get the SOA records, will not result in answer within the API of dnspython. There is a result returned however. It's just that dnspython will not wrap the authorative section inside an answer record.

Here is a similar situation:
https://stackoverflow.com/questions/4066614/how-can-i-find-the-authoritative-dns-server-for-a-domain-using-dnspython

**Comment by darkoperator** [comment]
test the latest changes I made.  Also your pull request you are performing the DNS query via TCP instead of UDP any reason? also by not setting a timeout and there is no response the script will hang (happened to me before)

**Comment by darkoperator** [comment]
where you able to test the last changes I made?

**Comment by FrankSpierings** [comment]
Sorry for the late reply, I didn't have time to test it until today. It seems to work great. Thanks for the patch!

**Pull request closed without merging**
