### PR TITLE
Adding full bruteforce feature

### PR DESCRIPTION
**Pull request by pathetiq**
Hi,

I wanted to brute force subdomains with all possibilities and not just from a word list. With the added force_enum() function I set the default bruteforce length to three (3) for an optimal delay, but it can be use to brute force subdomain on of any length if time permits.

The function take the length (-l --length) and the charset (-k, --charset) 0 for alphanum, 1 for alpha, 2 for numeric, being alphanumeric by default.

This is rather useful for red teaming or bug bounty hunting to find hidden or forgotten subdomains that might host vulnerable code or services.  

Let me know if you have any question and if that make sense

Thanks

### CODE REVIEW

**Comment by darkoperator** [comment]
Will take a look at it tonight, need to setup a Python 3.2 and 2.8 system for testing that it works with both versions

**Comment by darkoperator** [comment]
for some reason it is only performing one single query at a time even when you are using the threading, can you verify this,

**Comment by pathetiq** [comment]
Will do thanks for the follow-up.

**Comment by binarycanary** [comment]
@darkoperator I believe I figured out the problem. Silly Python spacing. In the `dnsrecon.py` submitted by @pathetiq, lines 373 and 374 have the indentation matching the for loop above them. They need to be backed up one level so that waiting for completion only happens after the for loop has finished.

A quick way to confirm is to add this line after the `pool.add_task` on line 370:
`           print_error('Task added, current pool count: {}'.format(pool.count()))`

You'll see the pool count go up to 1 and stay there. After you fix the indentation of lines 373 and 374 by bringing them out a level you can see the pool count go up.

Cheers,
DG
@decidedlygray

**Comment by pathetiq** [comment]
@binarycanary Thanks a lot for finding the problem, was overloaded and didn't have time to checked yet, Did the fixed with a quick tesst and you're right I wrongly ident the wait for threads which wait after only 1 thread was started.

**Comment by binarycanary** [comment]
@pathetiq, following up. Since the merge of error checking in #60, I think you'll also need to add 'force' to the list valid_types in order to allow it to be run as a valid scan type

**Comment by CerebralMischief** [comment]
Greetings, I'm curious about the status of this PR?  It was last commented on back in 2016.  Just wanted to bump this to gain your attention @darkoperator. :)  Hope you're doing well.

**Comment by arrowd** [comment]
Hello, any progress on this?

**Comment by darkoperator** [comment]
sorry for not addressing this before, I need to fix some merging conflicts by hand on the PR and get this added.

**Comment by CerebralMischief** [comment]
@darkoperator Thank you for spending time to create this tool.  I use it very frequently and was wondering if you would be interested in getting some assistance in maintaining this project?  Thank you in advance!

**Comment by L1ghtn1ng** [comment]
closing this out as will need redoing with the latest code changes

**Pull request closed without merging**
