### PR TITLE
Bug fix brute tld.

### PR DESCRIPTION
**Pull request by McFacePunch**
Attempting to address bug: https://github.com/darkoperator/dnsrecon/issues/213

Solution: Remove zip and use two sets of nested loops to handle the initialisation and completion.

I'm not 100% convinced this is a complete fix so someone else doing testing as well would be nice.

`dnsrecon.py -d microsoft.com -n 8.8.8.8 -f -a -s --threads 16 --lifetime 4 -c results.csv --disable_check_recursion -t tld -v` should be good enough, might want to tune threads though as google/cloudflare will rate limit you hard at a certain point.

Future upgrade would be to write output to a file as each thread is complete since this process takes insanely long to finish.

### CODE REVIEW

**Comment by McFacePunch** [comment]
Also hi again @L1ghtn1ng

**Comment by L1ghtn1ng** [comment]
Would using asyncio help in this case as I think it might?

**Comment by L1ghtn1ng** [comment]
> Also hi again @L1ghtn1ng 

Hi 👋 ☺️

**Comment by L1ghtn1ng** [comment]
> Would using asyncio help in this case as I think it might?

I mean in speeding it up so it does not take hopefully as long to run?

**Pull request merged**
