### PR TITLE
Feature: added -iL flag similar to nmap for passing a list of input domains

### PR DESCRIPTION
**Pull request by McFacePunch**
This implements: https://github.com/darkoperator/dnsrecon/issues/264

By using -iL in place of -d a user can specify domain name list by doing one line per domain

For example:
```
#domains.txt
dropbox.com
google.com
```

Command to run: `dnsrecon.py -iL domains.txt -t std -x output.xml -c output.csv -j output.json`

### CODE REVIEW

**Comment by McFacePunch** [comment]
@L1ghtn1ng did you change the ruff checks? Seems like it's complaining about things I hadn't even touched and also seems possibly wrong on the global variable bit.

**Comment by McFacePunch** [comment]
yeah I didn't even touch the files with current errors.

**Comment by L1ghtn1ng** [comment]
Yeah I did tweak the checks for ruff

**Comment by L1ghtn1ng** [comment]
Also I did touch the file it's complaining about so will fix that now

**Comment by L1ghtn1ng** [comment]
Pushed a change to fix ruff compliance and added loglevel argument

**Pull request merged**
